#include"stdio.h"
main()
	{
		int x=360,y=-1;
		long y1=-11;
		char *vb="programmer";
		double dx=3.14159265;
		clrscr();
		printf("\n\t            KET QUA PHU THUOC VAO DAC TA");
		printf("\n\t  *************************************************");
		printf("\n\t	*Gia tri goc cua X= 360");
		printf("\n-Neu dac ta la  010d thi X=%010d",x);
		printf("\n-Neu dac ta la -010d thi X=%-010d",x);
		printf("\n-Neu dac ta la   10o thi X=%10o",x);
		printf("\n-Neu dac ta la  010o thi X=%010o",x);
		printf("\n-Neu dac ta la  -10x thi X=%-10x",x);
		printf("\n-Neu dac ta la -010x thi X=%-010x",x);
		printf("\n\tBam phim bat ky de xem tiep");
		getch();
      printf("\n");
		printf("\n\t	*Gia tri goc cua Y= -1");
		printf("\n-Neu dac ta la 10d thi Y= %10d",y);
		printf("\n-Neu dac ta la 10u thi Y=	%10u",y);
		printf("\n-Neu dac ta la 10o thi Y= %10o",y);
		printf("\n-Neu dac ta la 10x thi Y=	%10x",y);
		printf("\n\tBam phim bat ky de xem tiep");
		getch();
      printf("\n");
		printf("\n\t	*Gia tri goc cua Y1=-11");
		printf("\n-Neu dac ta la 10ld thi Y1=%ld",y1);
		printf("\n-Neu dac ta la 10lu thi Y1=%10lu",y1);
		printf("\n-Neu dac ta la 10lo thi Y1=%10lo",y1);
		printf("\n-Neu dac ta la 10lx thi Y1=%10lx",y1);
      printf("\n\tBam phim bat ky de xem tiep");
		getch();
      printf("\n");
		printf("\n\t	*Gia tri goc cua DX=3.14159265");
		printf("\n-Neu dac ta la    010f  thi DX=%010f",dx);
		printf("\n-Neu dac ta la  010.3f  thi DX=%010.3f",dx);
		printf("\n-Neu dac ta la -010.3f  thi DX=%-010.3f",dx);
		printf("\n-Neu dac ta la   10.8f  thi DX=%10.8f",dx);
		printf("\n-Neu dac ta la   10.0f  thi DX=%10.0f",dx);
		printf("\n-Neu dac ta la     10g  thi DX=%10g",dx);
		printf("\n-Neu dac ta la     10e  thi DX=%10e",dx);
		printf("\n-Neu dac ta la   10.2e  thi DX=%10.2e",dx);
      printf("\n\tBam phim bat ky de xem tiep");
		getch();
      printf("\n");
		printf("\n\t	*Gia tri goc cua *VB=programmer");
		printf("\n-Neu dac ta la     10s thi VB=%10s",vb);
		printf("\n-Neu dac ta la   10.7s thi VB=%10.7s",vb);
		printf("\n-Neu dac ta la  -10.7s thi VB=%-10.7s",vb);
		printf("\n-Neu dac ta la  010.4s thi VB=%010.4s",vb);
		printf("\n-Neu dac ta la   10.0s thi VB=%10.0s",vb);
		printf("\n-Neu dac ta la     .3s thi VB=%.3s",vb);
		printf("\n-Neu dac ta la -010.3s thi VB=%-010.3s",vb);
		printf("\n\tBam phim bat ky de ket thuc");
		getch();
	}